spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/study_iot
    username: root
    password: root

    banner:
      location: classpath:banner.txt